// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ashcdguqtiiwszijqekt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzaGNkZ3VxdGlpd3N6aWpxZWt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNzUxMTUsImV4cCI6MjA2MTc1MTExNX0.oW80DPBGcUXVF7eocNqcjZZvaDf4rZ0DKtorvO98TZ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);